### ISSUE TITLE
[ENHANCEMENT] Create Evaluation and Generation Scripts

### ISSUE THREAD

**Issue by Quentin-Anthony** [Zyphra/Megatron-LM#11]
- [x] Create benchmarking script that loads a checkpoint and runs a set of tasks using the [lm-eval-harness](https://github.com/EleutherAI/lm-evaluation-harness)
- [x] Create inference script to test generation

Part of this task is just to see what's out there and what we can build on top of, if anything. I see:
- https://github.com/Zyphra/Megatron-LM/tree/main/tasks
- https://github.com/Zyphra/Megatron-LM/blob/main/tools/text_generation_cli.py
- https://github.com/Zyphra/Megatron-LM/blob/main/tools/run_text_generation_server.py
- https://github.com/Zyphra/Megatron-LM/blob/main/docs/llama2.md
- https://github.com/search?q=repo%3Amicrosoft%2FMegatron-DeepSpeed%20harness&type=code

For the harness, there appears to be nothing that we can just run, but plenty of similar examples that we can use to create our own eval harness scripts.

**Comment by BerenMillidge** [comment]
This is now done in the evaluation branch

**Comment by Quentin-Anthony** [comment]
> This is now done in the evaluation branch

If you've tested it, make a PR to main please.

**Comment by yury-tokpanov** [comment]
This is merged. A few things to keep in mind for future investigation:
- Not tested with different parallelization strategies 
- The evaluator is running on all ranks and produces slightly different results (within reported stddev)
- Is there a more efficient way of running evaluation? Unfortunately, it seems like both `megatron-deepspeed` and `gpt-neox` implementations are running on all ranks and then simply taking results from some rank (0th in case of `gpt-neox`).
