### ISSUE TITLE
[ENHANCEMENT] Run evals on our MoE and Dense checkpoints

### ISSUE THREAD

**Issue by Quentin-Anthony** [Zyphra/Megatron-LM#9]
We have checkpoints now for 760M dense and MoE models, we need to hook it up with the [lm eval harness](https://github.com/EleutherAI/lm-evaluation-harness) and run evaluations. I would like to compare with the [OpenMoE suite](https://github.com/XueFuzhao/OpenMoE) as well as the [open llm leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard)

@BerenMillidge -- Can you follow up with @eric-weiss-zyphra and share the checkpoint locations for him to run? 

@eric-weiss-zyphra -- Post back here with eval results once you have them.

**Comment by BerenMillidge** [comment]
Hey Eric sorry I thought Quentin had already discussed with you in more detail. Here are the models I think it would be good to evaluate:

1.) The MLM 760M dense model. This is to sanity check that our dense model is computing and converging well. The checkpoints are at: /home/cirrascale/home/beren/cirrascale/workspace/ckpts
on node 64.156.70.216

2.) Our 125M 32E models we trained last night. The 4e-5 125M checkpoints are inside the Megatron docker container on node 64.156.70.219 at /workspace/ckpts you should see checkpoint iter__30000

**Comment by Quentin-Anthony** [comment]
This is completed
